#!/bin/bash
# Runs inside the container (see run.sh): /tools is this directory, /tree the
# tensorlib checkout being traced, /out where the traces go.
set -euo pipefail

build=/tmp/build
mkdir -p "$build"

# The kernel table comes from the traced tree's own .cu, so a kernel added or
# re-ordered there is known here without anyone editing a list.
python3 /tools/gen_kernel_sigs.py /tree/kernels/tensorlib_cuda.cu > "$build/kernel_sigs.inc"
g++ -std=c++17 -O1 -shared -fPIC -I"$build" /tools/fake_libcuda.cpp -o "$build/libcuda.so.1"

# The PTX is nvcc's output and the fake driver never reads it: one zero byte
# stands in for the generated byte list.
echo 0x00 > "$build/tensorlib_cuda_ptx.inc"

flags=(-std=c++23 -O0 -w -DTENSORLIB_CUDA -I/tree/include -I"$build")
compile() {  # name, sources...
  local name=$1
  shift
  g++ "${flags[@]}" "$@" -ldl -o "$build/$name"
}
sweep=/tree/bench/cuda/check/trace_sweep.cpp
pids=()
compile tensorlib_test /tree/test/test_basic.cpp /tree/test/test_array.cpp & pids+=($!)
compile check_cuda /tree/bench/cuda/check/check_cuda.cpp & pids+=($!)
compile check_llm_decode /tree/bench/cuda/check/check_llm_decode.cpp & pids+=($!)
compile check_attn64 /tree/bench/cuda/check/check_attn64.cpp & pids+=($!)
# The sweep lives in the traced tree, beside the API it calls; a base that
# predates it simply has no sweep trace.
if [ -f "$sweep" ]; then
  compile trace_sweep "$sweep" & pids+=($!)
fi
for pid in "${pids[@]}"; do wait "$pid"; done  # a bare `wait` hides a failed compile

# The rest of bench/cuda is CUDA-only and runs nowhere here; that it still
# compiles against the headers is worth knowing before CI says so.
pids=()
for src in /tree/bench/cuda/speed/*.cpp; do
  grep -q '#include <cu' "$src" && continue  # needs the CUDA toolkit's headers
  g++ "${flags[@]}" -I/tree/bench/cuda -fsyntax-only "$src" &
  pids+=($!)
done
for pid in "${pids[@]}"; do wait "$pid"; done

# No kernel runs, so every numeric check in these programs fails; that is
# expected and their exit status says nothing. A signal is a different matter:
# it means the trace stops short.
trace() {  # name, args...
  local name=$1
  shift
  local status=0
  LD_LIBRARY_PATH="$build" TL_CUDA_TRACE="/out/$name.trace" \
    "$build/${name%%.*}" "$@" > "/out/$name.log" 2>&1 || status=$?
  if [ "$status" -ge 128 ]; then
    echo "cuda_trace: $name died on signal $((status - 128)); see $name.log" >&2
    exit 1
  fi
  if grep -aq 'UNRESOLVED\|^nofunc' "/out/$name.trace"; then
    echo "cuda_trace: $name passed the driver a pointer outside every allocation, or asked for an unknown kernel" >&2
    grep -an 'UNRESOLVED\|^nofunc' "/out/$name.trace" | head -5 >&2
    exit 1
  fi
}
trace tensorlib_test.gpu --gpu
trace tensorlib_test.auto --auto
trace check_cuda
trace check_llm_decode
trace check_attn64
if [ -f "$sweep" ]; then trace trace_sweep; fi

# Which kernels the traces reach, against every kernel the .cu defines.
grep -aho '^launch [a-z0-9_]*' /out/*.trace | sort -u | cut -d' ' -f2 > /out/kernels_reached.txt
grep -o '"tl_[a-z0-9_]*"' "$build/kernel_sigs.inc" | cut -d'"' -f2 | sort -u \
  | grep -vxFf /out/kernels_reached.txt > /out/kernels_unreached.txt || true
echo "cuda_trace: $(wc -l < /out/kernels_reached.txt) kernels reached, $(wc -l < /out/kernels_unreached.txt) not"
