#!/usr/bin/env bash
# WGSL -> C string literal, the WebGPU counterpart of the CUDA backend's
# bin2c step. Run this after editing tensorlib_webgpu.wgsl and commit the
# result: the wasm build is a flat emcc line that never runs CMake, so the
# .inc cannot be a build-time artifact the way the PTX one is.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
SRC="$HERE/tensorlib_webgpu.wgsl"
OUT="$HERE/tensorlib_webgpu_wgsl.inc"

{
  echo "// Generated by gen_wgsl_inc.sh from tensorlib_webgpu.wgsl -- do not edit."
  echo 'R"WGSL('
  cat "$SRC"
  echo ')WGSL"'
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
