#!/usr/bin/env bash
# Build the WebGPU spike. Usage: ./build.sh [asyncify|jspi|asyncify-only]
set -euo pipefail

MODE="${1:-asyncify}"
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
OUT="$HERE/site"

source "${EMSDK_DIR:-$HOME/Projects/emsdk}/emsdk_env.sh" >/dev/null 2>&1

mkdir -p "$OUT"

# WGSL -> C string literal. Mirrors the bin2c step the CUDA backend uses for
# PTX; #embed is macOS/C23-only in practice and this has to build under wasm.
{
  echo '// Generated by build.sh -- do not edit.'
  echo 'static const char* kSgemmWgsl = R"WGSL('
  cat "$HERE/sgemm.wgsl"
  echo ')WGSL";'
} > "$HERE/sgemm_wgsl.inc"

case "$MODE" in
  asyncify)      ASYNC_FLAGS=(-sASYNCIFY=1 -sASYNCIFY_STACK_SIZE=65536) ;;
  # Restrict instrumentation to the WaitAny call chain. If this list is
  # sufficient, the cost of a synchronous flush() is bounded and does not scale
  # with the size of the interpreter linked alongside it.
  asyncify-only) ASYNC_FLAGS=(-sASYNCIFY=1 -sASYNCIFY_STACK_SIZE=65536
                              -sASYNCIFY_ADVISE=1) ;;
  # Exports that may suspend must be declared, so the JS side gets a promising
  # wrapper. The C++ call chain underneath stays ordinary synchronous code.
  jspi)          ASYNC_FLAGS=(-sJSPI=1
                              -sJSPI_EXPORTS=wgpu_spike_init,wgpu_spike_bench) ;;
  *) echo "unknown mode: $MODE" >&2; exit 1 ;;
esac

set -x
emcc -std=c++23 -O2 -fwasm-exceptions \
  --use-port=emdawnwebgpu \
  "${ASYNC_FLAGS[@]}" \
  -sSTACK_SIZE=16MB -sALLOW_MEMORY_GROWTH=1 -sINITIAL_MEMORY=64MB \
  -sMODULARIZE=1 -sEXPORT_ES6=1 -sEXPORT_NAME=createSpike \
  -sENVIRONMENT=web,worker \
  -sEXPORTED_FUNCTIONS=_wgpu_spike_init,_wgpu_spike_bench,_wgpu_spike_log,_malloc,_free \
  -sEXPORTED_RUNTIME_METHODS=ccall,cwrap,UTF8ToString \
  -I"$ROOT/include" -I"$HERE" \
  "$HERE/spike_main.cpp" \
  -o "$OUT/spike.js"
set +x

cp "$HERE/index.html" "$HERE/worker.js" "$OUT/"
ls -l "$OUT"
echo "wasm size: $(stat -f%z "$OUT/spike.wasm") bytes  (mode=$MODE)"
