// WebGPU backend spike for cpp-tensorlib.
//
// What this is proving, in order of how much it would hurt to get wrong:
//
//  1. gpu::flush() can keep its synchronous signature under wasm. Metal's
//     flush() is commit + waitUntilCompleted; WebGPU's queue submission is
//     fire-and-forget and readback is promise-based. The claim under test is
//     that wgpuInstanceWaitAny(timeoutNS > 0) restores a blocking wait, and
//     that the Asyncify instrumentation this needs is confined to the wait
//     call chain rather than smeared over the whole interpreter.
//  2. Device acquisition needs no async on the C++ side at all: JS hands us a
//     ready device via Module.preinitializedWebGPUDevice.
//  3. A hand-written WGSL sgemm is worth the trouble versus the scalar CPU
//     path that wasm currently falls back to.
//
// Deliberately standalone: nothing here touches include/, so the real backend
// can be shaped by what this measures rather than the other way round.

#include <emscripten.h>
#include <webgpu/webgpu_cpp.h>

#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <algorithm>
#include <cstdarg>
#include <cstring>
#include <cmath>
#include <string>
#include <vector>

#include "sgemm_wgsl.inc"  // const char* kSgemmWgsl, generated by build.sh

// The CPU baseline is tensorlib's own path, not a hand-rolled loop -- an
// honest speedup number has to be against the code the playground runs today.
#include <tensorlib.h>

namespace {

struct Gpu {
  wgpu::Instance instance;
  wgpu::Device device;
  wgpu::Queue queue;
  wgpu::ComputePipeline pipeline;
  wgpu::BindGroupLayout bgl;
  bool ready = false;
} g;

std::string g_log;

void logf(const char* fmt, ...) {
  char buf[1024];
  va_list ap;
  va_start(ap, fmt);
  vsnprintf(buf, sizeof(buf), fmt, ap);
  va_end(ap);
  g_log += buf;
  g_log += '\n';
  printf("%s\n", buf);
}

// Blocking wait on a single future. This is the whole ballgame: every
// synchronous-looking call below bottoms out here, and here alone.
bool wait(wgpu::Future f) {
  auto st = g.instance.WaitAny(f, UINT64_MAX);
  return st == wgpu::WaitStatus::Success;
}

double now_ms() {
  return std::chrono::duration<double, std::milli>(
             std::chrono::steady_clock::now().time_since_epoch())
      .count();
}

}  // namespace

extern "C" {

EMSCRIPTEN_KEEPALIVE int wgpu_spike_init() {
  g_log.clear();

  // TimedWaitAny is what makes WaitAny(timeout > 0) legal. emdawnwebgpu
  // refuses to create the instance if Asyncify/JSPI is absent, so a link
  // without -sASYNCIFY fails loudly here instead of deadlocking later.
  wgpu::InstanceFeatureName features[] = {
      wgpu::InstanceFeatureName::TimedWaitAny};
  wgpu::InstanceDescriptor idesc = {};
  idesc.requiredFeatureCount = 1;
  idesc.requiredFeatures = features;

  g.instance = wgpu::CreateInstance(&idesc);
  if (!g.instance) {
    logf("FAIL: CreateInstance returned null (TimedWaitAny unavailable -- "
         "was this linked without -sASYNCIFY / -sJSPI?)");
    return 0;
  }
  logf("ok: instance created with TimedWaitAny");

  // No adapter/device request round-trip: JS already did it.
  g.device = wgpu::Device::Acquire(emscripten_webgpu_get_device());
  if (!g.device) {
    logf("FAIL: no preinitialized device (JS must set "
         "Module.preinitializedWebGPUDevice before calling in)");
    return 0;
  }
  g.queue = g.device.GetQueue();
  logf("ok: device acquired synchronously from JS");

  wgpu::ShaderSourceWGSL wgsl = {};
  wgsl.code = kSgemmWgsl;
  wgpu::ShaderModuleDescriptor smd = {};
  smd.nextInChain = &wgsl;
  wgpu::ShaderModule module = g.device.CreateShaderModule(&smd);

  wgpu::ComputePipelineDescriptor pd = {};
  pd.compute.module = module;
  pd.compute.entryPoint = "sgemm";
  g.pipeline = g.device.CreateComputePipeline(&pd);
  if (!g.pipeline) {
    logf("FAIL: CreateComputePipeline returned null");
    return 0;
  }
  g.bgl = g.pipeline.GetBindGroupLayout(0);
  logf("ok: WGSL sgemm compiled");

  g.ready = true;
  return 1;
}

}  // extern "C"

// Resources for one problem size, created once and reused across timed
// iterations. The real backend pools buffers the way metal.h does with its
// size-keyed free list, so folding allocation into every measurement would
// charge the GPU for a cost the shipping code does not pay.
struct Gemm {
  wgpu::Buffer a, b, c, params, staging;
  wgpu::BindGroup bg;
  int M = 0, N = 0, K = 0;
  uint64_t cbytes = 0;
};

namespace {

wgpu::Buffer mkbuf(uint64_t size, wgpu::BufferUsage usage) {
  wgpu::BufferDescriptor d = {};
  d.size = size;
  d.usage = usage;
  return g.device.CreateBuffer(&d);
}

struct Params {
  uint32_t M, N, K;
  float scale, offset;
  uint32_t pad0, pad1, pad2;
};

Gemm prepare(const float* a, const float* b, int M, int N, int K) {
  Gemm r;
  r.M = M; r.N = N; r.K = K;
  const uint64_t abytes = uint64_t(M) * K * 4;
  const uint64_t bbytes = uint64_t(K) * N * 4;
  r.cbytes = uint64_t(M) * N * 4;

  r.a = mkbuf(abytes, wgpu::BufferUsage::Storage | wgpu::BufferUsage::CopyDst);
  r.b = mkbuf(bbytes, wgpu::BufferUsage::Storage | wgpu::BufferUsage::CopyDst);
  r.c = mkbuf(r.cbytes, wgpu::BufferUsage::Storage | wgpu::BufferUsage::CopySrc);
  r.params = mkbuf(sizeof(Params),
                   wgpu::BufferUsage::Uniform | wgpu::BufferUsage::CopyDst);
  r.staging = mkbuf(r.cbytes,
                    wgpu::BufferUsage::MapRead | wgpu::BufferUsage::CopyDst);

  Params p = {uint32_t(M), uint32_t(N), uint32_t(K), 1.0f, 0.0f, 0, 0, 0};
  // WriteBuffer is synchronous from the caller's point of view -- the copy is
  // queued, not awaited. No suspend cost on the upload path.
  g.queue.WriteBuffer(r.a, 0, a, abytes);
  g.queue.WriteBuffer(r.b, 0, b, bbytes);
  g.queue.WriteBuffer(r.params, 0, &p, sizeof(p));

  wgpu::BindGroupEntry e[4] = {};
  e[0].binding = 0; e[0].buffer = r.a; e[0].size = abytes;
  e[1].binding = 1; e[1].buffer = r.b; e[1].size = bbytes;
  e[2].binding = 2; e[2].buffer = r.c; e[2].size = r.cbytes;
  e[3].binding = 3; e[3].buffer = r.params; e[3].size = sizeof(Params);
  wgpu::BindGroupDescriptor bgd = {};
  bgd.layout = g.bgl;
  bgd.entryCount = 4;
  bgd.entries = e;
  r.bg = g.device.CreateBindGroup(&bgd);
  return r;
}

// One dispatch plus a blocking wait -- this is exactly the shape gpu::flush()
// has to keep. Returns elapsed ms.
double dispatch(const Gemm& r) {
  double t0 = now_ms();
  auto enc = g.device.CreateCommandEncoder();
  auto pass = enc.BeginComputePass();
  pass.SetPipeline(g.pipeline);
  pass.SetBindGroup(0, r.bg);
  pass.DispatchWorkgroups((r.N + 63) / 64, (r.M + 63) / 64, 1);
  pass.End();
  auto cmds = enc.Finish();
  g.queue.Submit(1, &cmds);
  if (!wait(g.queue.OnSubmittedWorkDone(
          wgpu::CallbackMode::WaitAnyOnly,
          [](wgpu::QueueWorkDoneStatus, wgpu::StringView) {}))) {
    return -1.0;
  }
  return now_ms() - t0;
}

// sync_to_host(): map, copy, unmap -- all behind a synchronous signature.
bool readback(const Gemm& r, float* out) {
  auto enc = g.device.CreateCommandEncoder();
  enc.CopyBufferToBuffer(r.c, 0, r.staging, 0, r.cbytes);
  auto cmds = enc.Finish();
  g.queue.Submit(1, &cmds);

  bool ok = false;
  if (!wait(r.staging.MapAsync(wgpu::MapMode::Read, 0, r.cbytes,
                               wgpu::CallbackMode::WaitAnyOnly,
                               [&ok](wgpu::MapAsyncStatus s, wgpu::StringView) {
                                 ok = (s == wgpu::MapAsyncStatus::Success);
                               })) ||
      !ok) {
    logf("FAIL: MapAsync wait failed");
    return false;
  }
  const void* src = r.staging.GetConstMappedRange(0, r.cbytes);
  if (!src) {
    logf("FAIL: GetConstMappedRange returned null");
    return false;
  }
  memcpy(out, src, r.cbytes);
  r.staging.Unmap();
  return true;
}

double median(std::vector<double> v) {
  std::sort(v.begin(), v.end());
  return v[v.size() / 2];
}

}  // namespace

extern "C" {

EMSCRIPTEN_KEEPALIVE const char* wgpu_spike_log() { return g_log.c_str(); }

// Correctness against tensorlib's CPU path, then an interleaved A/B at a few
// sizes. Interleaved because a straight "all GPU then all CPU" ordering lets
// thermal drift masquerade as a speedup.
EMSCRIPTEN_KEEPALIVE int wgpu_spike_bench() {
  if (!g.ready) return 0;

  auto fill = [](std::vector<float>& v, int mul, int mod) {
    for (size_t i = 0; i < v.size(); ++i)
      v[i] = float((i * mul) % mod) / float(mod) - 0.5f;
  };

  // Warm both paths before recording anything. The first GPU dispatch pays
  // lazy pipeline setup and the first tensorlib eval pays its own one-time
  // costs; without this the smallest size absorbs both and reads as the
  // slowest, which is exactly backwards.
  {
    const int w = 128;
    std::vector<float> a(size_t(w) * w), b(size_t(w) * w), o(size_t(w) * w);
    fill(a, 37, 101);
    fill(b, 53, 97);
    Gemm r = prepare(a.data(), b.data(), w, w, w);
    dispatch(r);
    readback(r, o.data());
    tl::use_cpu();
    tl::array::from(a, {w, w}).dot(tl::array::from(b, {w, w})).eval();
    logf("(warmup done)");
  }

  logf("%-6s %22s %22s %8s %10s", "n", "gpu", "cpu (tensorlib)", "speedup",
       "maxerr");

  const int sizes[] = {128, 256, 512, 1024};
  for (int n : sizes) {
    std::vector<float> a(size_t(n) * n), b(size_t(n) * n), gpu(size_t(n) * n);
    fill(a, 37, 101);
    fill(b, 53, 97);

    Gemm r = prepare(a.data(), b.data(), n, n, n);

    // The CPU path is slow enough at n=1024 (tens of seconds, scalar wasm)
    // that repeating it is not worth the wall clock; the GPU side is cheap so
    // it gets a proper median.
    const int greps = 7;
    const int creps = n >= 1024 ? 1 : 3;

    tl::use_cpu();
    auto ta = tl::array::from(a, {n, n});
    auto tb = tl::array::from(b, {n, n});

    std::vector<double> gt, ct;
    tl::array tc;
    // Interleaved: alternate GPU and CPU reps so thermal drift or a background
    // tab hits both arms rather than whichever ran second.
    for (int i = 0; i < std::max(greps, creps); ++i) {
      if (i < greps) {
        double ms = dispatch(r);
        if (ms < 0) { logf("FAIL: dispatch failed at n=%d", n); return 0; }
        gt.push_back(ms);
      }
      if (i < creps) {
        double c0 = now_ms();
        tc = ta.dot(tb).eval();
        ct.push_back(now_ms() - c0);
      }
    }

    if (!readback(r, gpu.data())) return 0;

    // Tolerance is loose-ish: the WGSL kernel accumulates in a different order
    // than the CPU microkernel, and f32 sgemm drifts accordingly as K grows.
    const float* ref = tc.raw();
    double maxerr = 0.0;
    for (size_t i = 0; i < gpu.size(); ++i) {
      double e = std::abs(double(gpu[i]) - double(ref[i]));
      if (e > maxerr) maxerr = e;
    }

    double gms = median(gt), cms = median(ct);
    double gflop = 2.0 * n * n * n / 1e9;
    logf("n=%-5d %8.2f ms %8.1f GF/s %8.1f ms %8.2f GF/s %7.1fx %10.2e", n,
         gms, gflop / (gms / 1e3), cms, gflop / (cms / 1e3), cms / gms, maxerr);
    if (maxerr > 1e-2) {
      logf("FAIL: n=%d exceeds tolerance", n);
      return 0;
    }
  }
  return 1;
}

}  // extern "C"
